### ISSUE TITLE
Your default character set does not match your examples, and all other converters out there 

### ISSUE THREAD

**Issue by michaelhoefer** [andrew/base62.js#18]
FYI, this tripped me up for a bit.  You use G7 converting to 999 in your example.  But with your default character set, decode('G7') == 2611.

You need to run:
b.setCharacterSet('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz');
to get decode('G7') == 999

**Comment by andrew** [comment]
@michaelhoefer `G7` is different from `g7` which is used in the readme as Base62 encoded values are case sensitive.

Just double checked the default in the readme:

![screen shot 2016-12-15 at 1 01 39 pm](https://cloud.githubusercontent.com/assets/1060/21225045/108d6292-c2c7-11e6-9e4b-6dd7d87c145e.png)
