### ISSUE TITLE
`TID` is not recognized command.

### ISSUE THREAD

**Issue by Gopikrishna19** [andrew/base62.js#63]
@andrew I just now saw that you have released a patch to fix this error by adding a fallback. This error was happening to me in windows, but passed in linux. Why not use [`cross-env`](https://www.npmjs.com/package/cross-env)? This package will enable to use same command line environment variables.

Thank you for immediately fixing the issue!

**Comment by andrew** [comment]
@Gopikrishna19 that looks great, I was thinking of switching from using an environment variable to an argument instead which might avoid adding an extra dependency

**Comment by Gopikrishna19** [comment]
Arguments are awesome, and no more cross platform issues!
