### ISSUE TITLE
Is it possible to disable install-stats.js?

### ISSUE THREAD

**Issue by eu81273** [andrew/base62.js#66]
base62.js is one of dependency in my project. :)

I have one problem with install-stats.js in base62/scripts.
Internal network case, because install-stats.js tries to connect google analytics, so npm install takes too long time, and fails to connect in the end.
This makes build time to be increased.

Could you add timeout for this process or give any option to disable it?

**Comment by bfdill** [comment]
+1 We're having the same problem, and builds are slowing down.  Please add a flag or something to disable this.

**Comment by rafaelmlourenco** [comment]
Edited package.json and created the pull request #67, to remove Google Analytics dependency for now

**Comment by 131** [comment]
@isaacs Is there an NPM stance on this subject ?
