### ISSUE TITLE
Where is the tag for 1.2.8?

### ISSUE THREAD

**Issue by willdurand** [andrew/base62.js#74]
Hi, I see that a version `1.2.8` is listed on npm but I cannot find the tag here. Could you push it by chance? Thanks.

**Comment by FND** [comment]
That would have to be 4fc9dafeefa53ba4b81d4bca12b8ffef346bcdcb, as that's [the only commit](https://github.com/andrew/base62.js/compare/v1.2.7...master) between v1.2.7 and when I started contributing towards v2.0.0 - but I'll leave it to @andrew to confirm that.

**Comment by andrew** [comment]
I have no idea 😂

**Comment by andrew** [comment]
I’d recommend using 2.0.0

**Comment by willdurand** [comment]
> I have no idea 😂

oh, heh.

> I’d recommend using 2.X

Yep, but our test suite fails when upgrading from `1.2.8` to `2.0.0` (using the legacy API). It seem an invalid data to decode does not throw any error anymore and we get `NaN` instead. I am not sure though.

**Comment by andrew** [comment]
Maybe it's worth changing the title of the issue to report that bug instead?

**Comment by andrew** [comment]
@willdurand as I mentioned before, I don't know where to put that tag as it was a long time ago.

**Comment by FND** [comment]
@andrew: I've just checked against the contents of the npm package and I'm fairly certain that the commit I'd identified above was in fact v1.2.8 - do you mind if I create that tag retroactively?

**Comment by andrew** [comment]
@FND sure

**Comment by FND** [comment]
Done: https://github.com/andrew/base62.js/commits/v1.2.8

Hope that helps, @willdurand.
